blog/urls.py
from django.urls import path
from .views import render_posts, post_detail


app_name ='blog'
urlpatterns = [
    path('', render_posts,name='posts'),path('<int:post_id>',post_detail, name='post_detail')
]
    

pf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Tem import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Tem/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    image = ImageField(upload_to="Timjg/imagen")  # Crea carpeta y la guarda  en imagen
    url = URLField(blank=True)

blog/models.py
from django.db import models
import datetime
from django_quill.fields import QuillField

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = QuillField(
        default='<p></p>',  
        blank=True,
        null=True,
        
    )
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(default=datetime.date.today)

Tem/views.py
from django.shortcuts import render
from .models import Project
def home(request):
    projects = Project.objects.all()
    return render(request,'home.html', {'projects': projects})
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    return render(request, 'post_detail.html',{'post': post})

Tem/templates/home.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'porfolio/Presentation.jpg' %}" alt="" width="300" height="200">
    </div>

    <div class="col-md-8 my-auto">
        <h1> Bienvenidos a <strong>BlogShare</strong> </h1>
        <p> 
            Esta página web ha sido creada como una plataforma de blog, donde los usuarios, incluyendo profesores, pueden subir y publicar sus propios contenidos. El objetivo principal 
            es brindar un espacio donde se puedan compartir conocimientos, 
            ideas e inspiraciones con una audiencia más amplia.
        </p>
        <a href="{% static 'porfolio/Acerca de.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3"> Mas informacion</a>
    </div>
</header>

<div class="row my-4 text-center p-4">
    <h3>proyectos </h3>
    <p>Ven y explora los proyectos subidos! </p>
{%for project in projects %}

    <div class="col my-4">
        <div class="card bg-black card-project">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
                <h2 class="text-white">{{project.title}}</h2>
                <p class="text-white" >{{project.descripcion.html}}</p>
                

                {% if project.url %}
                    <a href="{{project.url}}" class="btn btn-secondary rounded-0 btn-sm" target="_blank">{{project.url}}</a>

                {% endif %}
            </div>

        </div>
    </div>

{% endfor %}

{% endblock %}

</div>

Tem/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sala Principal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>
   
</body>
</html>

Tem/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-ital" href="/">AA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/blog" target="_blank">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sn" href="{% static 'porfolio/Acerca de.pdf' %}">Mas informacion</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-white">{{post.date|date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fuild" width="600" height="400">

    <div class="my-4">
        <div>{{ post.description.html|safe }}</div>

    </div>
</div>


{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
<h1>Publicaciones</h1>
{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">

            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fuild" width="200" height="100">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <div >{{ post.description|safe }}</div>
                <p class="text-white">{{post.date|date:'M d Y'|upper}}</p>
                <a href="{% url 'blog:post_detail' post.id  %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
        
    </div>
</div>

{% endfor %}

{% endblock %}
 